const predefinedResponses = {
    "hello": "Hello! How can I assist you today?",
    "hi": "Hi there! How can I help?",
    "how are you": "I'm just a program, but I'm here to make your day better!",
    "joke": "Why did the programmer quit their job? Because they didn't get arrays!",
    "bye": "Goodbye! Have a great day!",
    "draft": "Sure, let's start drafting your idea!",
    "advice": "Here's some advice: Always write clean and maintainable code!",
    "learn": "Learning is great! What topic are you interested in?",
    "image": "I can't create images yet, but I can help you brainstorm ideas for one!",
    "plan": "Let's make a plan! What are your goals?",
    "brainstorm": "I'm ready to brainstorm! What's the topic?",
    "language": "Practicing a language is fun! Which language are you learning?",
    "quiz": "Let's take a quiz! What topic should it be about?",
    "who is jackson": "Jackson is the one who created me!",
    "who is you": "I'm your friendly AI assistant, here to help you!",
    "who is me": "You are the one using this chat!",
    "who is": "I don't know who you are, but I'm here to help!",
    "who are you": "I'm your AI assistant!",
    "who": "I am an AI assistant created to help you with your queries!",
    "what is": "I can help you with a lot of things! What do you want to know?",
    "what": "I can assist you with various topics! What do you need help with?",
    "where": "I can help you find information! Where do you want to go?",
    "when": "I can help you with time-related queries! When do you need assistance?",
    "why": "I can help you understand things better! Why do you ask?",
    "how": "I can help you with various processes! How can I assist you?",
    "help": "I'm here to help! What do you need assistance with?",
    "thank you": "You're welcome! If you need anything else, just ask.",
    "thanks": "You're welcome! If you need anything else, just ask.",
    "please": "Of course! How can I assist you further?",
    "sorry": "No problem! I'm here to help you.",
    "yes": "Great! How can I assist you?",
    "no": "Alright! If you change your mind, I'm here to help.",
    "maybe": "That's a possibility! Let me know if you need anything.",
    "sure": "Absolutely! How can I assist you?",
    "okay": "Okay! What would you like to know?",
    "ok": "Okay! What would you like to know?",
    "goodbye": "Goodbye! Have a great day!",
    "good night": "Good night! Sleep well!",
    "good morning": "Good morning! How can I help you today?",
    "good afternoon": "Good afternoon! How can I assist you?",
    "good evening": "Good evening! How can I assist you?",
    "good": "Good! How can I assist you?",
    "bad": "I'm sorry to hear that. How can I help you feel better?",
    "sad": "I'm here for you. How can I help?",
    "happy": "That's great to hear! How can I assist you further?",
    "angry": "I understand. How can I help you feel better?",
    "excited": "That's awesome! How can I assist you further?",
    "bored": "Let's find something fun to do! What are you interested in?",
    "tired": "I understand. Maybe take a break? How can I assist you?",
    "hungry": "What are you in the mood for? I can help you find something to eat!",
    "thirsty": "What would you like to drink? I can help you find something refreshing!",
    "busy": "I understand. Let me know when you're free to chat!",
    "free": "Great! I'm here to help you with anything you need.",
    "love": "That's wonderful! Love is a beautiful thing.",
    "hate": "I'm sorry to hear that. How can I help you feel better?",
    "like": "That's great! What do you like about it?",
    "dislike": "I'm sorry to hear that. How can I help you feel better?",
    "favorite": "That's awesome! What's your favorite thing?",
    "least favorite": "I'm sorry to hear that. How can I help you feel better?",
    "best": "That's great! What's the best thing about it?",
    "worst": "I'm sorry to hear that. How can I help you feel better?",
    "best friend": "That's wonderful! Friends are important.",
    "write a first draft": "Sure! What topic should I write about?",
    "write a second draft": "Sure! What topic should I write about?",
    "write a third draft": "Sure! What topic should I write about?",
    "write a final draft": "Sure! What topic should I write about?",
    "write a summary": "Sure! What topic should I summarize?",
    "write a conclusion": "Sure! What topic should I conclude?",
    "write an introduction": "Sure! What topic should I introduce?",
    "write a paragraph": "Sure! What topic should I write about?",
    "write a sentence": "Sure! What topic should I write about?",
    "write a word": "Sure! What topic should I write about?",
    "write a letter": "Sure! What topic should I write about?",
    "write an email": "Sure! What topic should I write about?",
    "write a message": "Sure! What topic should I write about?",
    "write a text": "Sure! What topic should I write about?",
    "get advice": "Sure! What do you need advice on?",
    "get help": "Sure! What do you need help with?",
    "get information": "Sure! What do you need information on?",
    "get tips": "Sure! What do you need tips on?",
    "get suggestions": "Sure! What do you need suggestions on?",
    "get recommendations": "Sure! What do you need recommendations on?",
    "get feedback": "Sure! What do you need feedback on?",
    "get reviews": "Sure! What do you need reviews on?",
    "get ratings": "Sure! What do you need ratings on?",
    "get scores": "Sure! What do you need scores on?",
    "get grades": "Sure! What do you need grades on?",
    "get marks": "Sure! What do you need marks on?",
    "get points": "Sure! What do you need points on?",
    "get credits": "Sure! What do you need credits on?",
    "get awards": "Sure! What do you need awards on?",
    "get honors": "Sure! What do you need honors on?",
    "get achievements": "Sure! What do you need achievements on?",
    "get accomplishments": "Sure! What do you need accomplishments on?",
    "get milestones": "Sure! What do you need milestones on?",
    "get goals": "Sure! What do you need goals on?",
    "get objectives": "Sure! What do you need objectives on?",
    "get targets": "Sure! What do you need targets on?",
    "get aims": "Sure! What do you need aims on?",
    "get purposes": "Sure! What do you need purposes on?",
    "get intentions": "Sure! What do you need intentions on?",
    "get plans": "Sure! What do you need plans on?",
    "get strategies": "Sure! What do you need strategies on?",
    "get tactics": "Sure! What do you need tactics on?",
    "get techniques": "Sure! What do you need techniques on?",
    "get methods": "Sure! What do you need methods on?",
    "get procedures": "Sure! What do you need procedures on?",
    "get processes": "Sure! What do you need processes on?",
    "get systems": "Sure! What do you need systems on?",
    "get structures": "Sure! What do you need structures on?",
    "get frameworks": "Sure! What do you need frameworks on?",
    "get models": "Sure! What do you need models on?",
    "get designs": "Sure! What do you need designs on?",
    "get blueprints": "Sure! What do you need blueprints on?",
    "get schematics": "Sure! What do you need schematics on?",
    "get diagrams": "Sure! What do you need diagrams on?",
    "get illustrations": "Sure! What do you need illustrations on?",
    "get images": "Sure! What do you need images on?",
    "get graphics": "Sure! What do you need graphics on?",
    "get visuals": "Sure! What do you need visuals on?",
    "get pictures": "Sure! What do you need pictures on?",
    "get photos": "Sure! What do you need photos on?",
    "get videos": "Sure! What do you need videos on?",
    "get audios": "Sure! What do you need audios on?",
    "get sounds": "Sure! What do you need sounds on?",
    "get music": "Sure! What do you need music on?",
    "get songs": "Sure! What do you need songs on?",
    "get lyrics": "Sure! What do you need lyrics on?",
    "get notes": "Sure! What do you need notes on?",
    "get reminders": "Sure! What do you need reminders on?",
    "get alerts": "Sure! What do you need alerts on?",
    "get notifications": "Sure! What do you need notifications on?",
    "get messages": "Sure! What do you need messages on?",
    "get texts": "Sure! What do you need texts on?",
    "get chats": "Sure! What do you need chats on?",
    "get conversations": "Sure! What do you need conversations on?",
    "get discussions": "Sure! What do you need discussions on?",
    "get debates": "Sure! What do you need debates on?",
    "get dialogues": "Sure! What do you need dialogues on?",
    "get interactions": "Sure! What do you need interactions on?",
    "get engagements": "Sure! What do you need engagements on?",
    "get connections": "Sure! What do you need connections on?",
    "get relationships": "Sure! What do you need relationships on?",
    "get partnerships": "Sure! What do you need partnerships on?",
    "get collaborations": "Sure! What do you need collaborations on?",
    "get alliances": "Sure! What do you need alliances on?",
    "get associations": "Sure! What do you need associations on?",
    "get networks": "Sure! What do you need networks on?",
    "get communities": "Sure! What do you need communities on?",
    "get groups": "Sure! What do you need groups on?",
    "get teams": "Sure! What do you need teams on?",
    "get squads": "Sure! What do you need squads on?",
    "get crews": "Sure! What do you need crews on?",
    "get gangs": "Sure! What do you need gangs on?",
    "get mobs": "Sure! What do you need mobs on?",
    "get crowds": "Sure! What do you need crowds on?",
    "get masses": "Sure! What do you need masses on?",
    "get throngs": "Sure! What do you need throngs on?",
    "get hordes": "Sure! What do you need hordes on?",
    "get flocks": "Sure! What do you need flocks on?",
    "get swarms": "Sure! What do you need swarms on?",
    "learn something new": "Learning is a continuous process! What would you like to learn about?",
    "learn a new skill": "That's great! What skill would you like to learn?",
    "learn a new language": "That's awesome! Which language are you interested in?",
    "learn a new topic": "That's great! What topic would you like to learn about?",
    "learn a new subject": "That's great! What subject would you like to learn about?",
    "learn a new hobby": "That's great! What hobby would you like to learn about?",
    "learn a new interest": "That's great! What interest would you like to learn about?",
    "learn a new activity": "That's great! What activity would you like to learn about?",
    "learn a new sport": "That's great! What sport would you like to learn about?",
    "learn a new game": "That's great! What game would you like to learn about?",
    "learn a new skillset": "That's great! What skillset would you like to learn about?",
    "learn a new technique": "That's great! What technique would you like to learn about?",
    "create an image": "I can't create images yet, but I can help you brainstorm ideas for one!",
    "create a plan": "Sure! What do you want to plan?",
    "create a draft": "Sure! What do you want to draft?",
    "create a document": "Sure! What do you want to document?",
    "make a plan": "Sure! What do you want to plan?",
    "make a draft": "Sure! What do you want to draft?",
    "make a document": "Sure! What do you want to document?",
    "make a schedule": "Sure! What do you want to schedule?",
    "make a timeline": "Sure! What do you want to timeline?",
    "make a calendar": "Sure! What do you want to calendar?",
    "make a list": "Sure! What do you want to list?",
    "make a chart": "Sure! What do you want to chart?",
    "make a graph": "Sure! What do you want to graph?",
    "make a table": "Sure! What do you want to table?",
    "make a diagram": "Sure! What do you want to diagram?",
    "make a drawing": "Sure! What do you want to draw?",
    "make a sketch": "Sure! What do you want to sketch?",
    "make a design": "Sure! What do you want to design?",
    "make a blueprint": "Sure! What do you want to blueprint?",
    "make a schematic": "Sure! What do you want to schematic?",
    "make a model": "Sure! What do you want to model?",
    "make a prototype": "Sure! What do you want to prototype?",
    "make a sample": "Sure! What do you want to sample?",
    "make a mockup": "Sure! What do you want to mockup?",
    "make a spreadsheet": "Sure! What do you want to spreadsheet?",
    "take a quiz": "Sure! What topic should the quiz be about?",
    "take a test": "Sure! What topic should the test be about?",
    "take an exam": "Sure! What topic should the exam be about?",
    "take a survey": "Sure! What topic should the survey be about?",
    "take a poll": "Sure! What topic should the poll be about?",
    "take a questionnaire": "Sure! What topic should the questionnaire be about?",
    "take a feedback": "Sure! What topic should the feedback be about?",
    "take a review": "Sure! What topic should the review be about?",
    "take a rating": "Sure! What topic should the rating be about?",
    "take a score": "Sure! What topic should the score be about?",
    "take a grade": "Sure! What topic should the grade be about?",
    "take a mark": "Sure! What topic should the mark be about?",
    "take a point": "Sure! What topic should the point be about?",
    "take a credit": "Sure! What topic should the credit be about?",
    "practise a language": "That's great! Which language are you practicing?",
    "can you remember what you say": "No, I can't remember what I say. I don't have memory.",
    "can you remember what i say": "No, I can't remember what you say. I don't have memory.",
};